CC = gcc
output1 = main_queue
output2 = main_stack
source11 = queue
source21 = stack
source2 = list
source3 = mm

all: $(output1)_int $(output1)_short $(output1)_long $(output1)_char $(output1)_float $(output1)_double $(output1)_ptr-to-int $(output1)_ptr-to-short $(output1)_ptr-to-long $(output1)_ptr-to-char $(output1)_ptr-to-float $(output1)_ptr-to-double\
	$(output2)_int $(output2)_short $(output2)_long $(output2)_char $(output2)_float $(output2)_double $(output2)_ptr-to-int $(output2)_ptr-to-short $(output2)_ptr-to-long $(output2)_ptr-to-char $(output2)_ptr-to-float $(output2)_ptr-to-double

$(output1)_int:
	$(CC) -o $(output1)_int ./int/$(output1)_int.c ./int/$(source11)_int.c ./int/$(source2)_int.c ./int/$(source3).c
$(output2)_int:
	$(CC) -o $(output2)_int ./int/$(output2)_int.c ./int/$(source21)_int.c ./int/$(source2)_int.c ./int/$(source3).c

$(output1)_short:
	$(CC) -o $(output1)_short ./short/$(output1)_short.c ./short/$(source11)_short.c ./short/$(source2)_short.c ./short/$(source3).c
$(output2)_short:
	$(CC) -o $(output2)_short ./short/$(output2)_short.c ./short/$(source21)_short.c ./short/$(source2)_short.c ./short/$(source3).c

$(output1)_long:
	$(CC) -o $(output1)_long ./long/$(output1)_long.c ./long/$(source11)_long.c ./long/$(source2)_long.c ./long/$(source3).c
$(output2)_long:
	$(CC) -o $(output2)_long ./long/$(output2)_long.c ./long/$(source21)_long.c ./long/$(source2)_long.c ./long/$(source3).c

$(output1)_char:
	$(CC) -o $(output1)_char ./char/$(output1)_char.c ./char/$(source11)_char.c ./char/$(source2)_char.c ./char/$(source3).c
$(output2)_char:
	$(CC) -o $(output2)_char ./char/$(output2)_char.c ./char/$(source21)_char.c ./char/$(source2)_char.c ./char/$(source3).c

$(output1)_float:
	$(CC) -o $(output1)_float ./float/$(output1)_float.c ./float/$(source11)_float.c ./float/$(source2)_float.c ./float/$(source3).c
$(output2)_float:
	$(CC) -o $(output2)_float ./float/$(output2)_float.c ./float/$(source21)_float.c ./float/$(source2)_float.c ./float/$(source3).c

$(output1)_double:
	$(CC) -o $(output1)_double ./double/$(output1)_double.c ./double/$(source11)_double.c ./double/$(source2)_double.c ./double/$(source3).c
$(output2)_double:
	$(CC) -o $(output2)_double ./double/$(output2)_double.c ./double/$(source21)_double.c ./double/$(source2)_double.c ./double/$(source3).c

$(output1)_ptr-to-int:
	$(CC) -o $(output1)_ptr-to-int ./ptr-to-int/$(output1)_ptr-to-int.c ./ptr-to-int/$(source11)_ptr-to-int.c ./ptr-to-int/$(source2)_ptr-to-int.c ./ptr-to-int/$(source3).c
$(output2)_ptr-to-int:
	$(CC) -o $(output2)_ptr-to-int ./ptr-to-int/$(output2)_ptr-to-int.c ./ptr-to-int/$(source21)_ptr-to-int.c ./ptr-to-int/$(source2)_ptr-to-int.c ./ptr-to-int/$(source3).c

$(output1)_ptr-to-short:
	$(CC) -o $(output1)_ptr-to-short ./ptr-to-short/$(output1)_ptr-to-short.c ./ptr-to-short/$(source11)_ptr-to-short.c ./ptr-to-short/$(source2)_ptr-to-short.c ./ptr-to-short/$(source3).c
$(output2)_ptr-to-short:
	$(CC) -o $(output2)_ptr-to-short ./ptr-to-short/$(output2)_ptr-to-short.c ./ptr-to-short/$(source21)_ptr-to-short.c ./ptr-to-short/$(source2)_ptr-to-short.c ./ptr-to-short/$(source3).c

$(output1)_ptr-to-long:
	$(CC) -o $(output1)_ptr-to-long ./ptr-to-long/$(output1)_ptr-to-long.c ./ptr-to-long/$(source11)_ptr-to-long.c ./ptr-to-long/$(source2)_ptr-to-long.c ./ptr-to-long/$(source3).c
$(output2)_ptr-to-long:
	$(CC) -o $(output2)_ptr-to-long ./ptr-to-long/$(output2)_ptr-to-long.c ./ptr-to-long/$(source21)_ptr-to-long.c ./ptr-to-long/$(source2)_ptr-to-long.c ./ptr-to-long/$(source3).c

$(output1)_ptr-to-char:
	$(CC) -o $(output1)_ptr-to-char ./ptr-to-char/$(output1)_ptr-to-char.c ./ptr-to-char/$(source11)_ptr-to-char.c ./ptr-to-char/$(source2)_ptr-to-char.c ./ptr-to-char/$(source3).c
$(output2)_ptr-to-char:
	$(CC) -o $(output2)_ptr-to-char ./ptr-to-char/$(output2)_ptr-to-char.c ./ptr-to-char/$(source21)_ptr-to-char.c ./ptr-to-char/$(source2)_ptr-to-char.c ./ptr-to-char/$(source3).c

$(output1)_ptr-to-float:
	$(CC) -o $(output1)_ptr-to-float ./ptr-to-float/$(output1)_ptr-to-float.c ./ptr-to-float/$(source11)_ptr-to-float.c ./ptr-to-float/$(source2)_ptr-to-float.c ./ptr-to-float/$(source3).c
$(output2)_ptr-to-float:
	$(CC) -o $(output2)_ptr-to-float ./ptr-to-float/$(output2)_ptr-to-float.c ./ptr-to-float/$(source21)_ptr-to-float.c ./ptr-to-float/$(source2)_ptr-to-float.c ./ptr-to-float/$(source3).c

$(output1)_ptr-to-double:
	$(CC) -o $(output1)_ptr-to-double ./ptr-to-double/$(output1)_ptr-to-double.c ./ptr-to-double/$(source11)_ptr-to-double.c ./ptr-to-double/$(source2)_ptr-to-double.c ./ptr-to-double/$(source3).c
$(output2)_ptr-to-double:
	$(CC) -o $(output2)_ptr-to-double ./ptr-to-double/$(output2)_ptr-to-double.c ./ptr-to-double/$(source21)_ptr-to-double.c ./ptr-to-double/$(source2)_ptr-to-double.c ./ptr-to-double/$(source3).c

clean:
	rm $(output1)_int $(output2)_int
	rm $(output1)_short $(output2)_short
	rm $(output1)_long $(output2)_long
	rm $(output1)_char $(output2)_char
	rm $(output1)_float $(output2)_float
	rm $(output1)_double $(output2)_double
	rm $(output1)_ptr-to-int $(output2)_ptr-to-int
	rm $(output1)_ptr-to-short $(output2)_ptr-to-short
	rm $(output1)_ptr-to-long $(output2)_ptr-to-long
	rm $(output1)_ptr-to-char $(output2)_ptr-to-char
	rm $(output1)_ptr-to-float $(output2)_ptr-to-float
	rm $(output1)_ptr-to-double $(output2)_ptr-to-double

